export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USER = 'GET_USER';
export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_RECIPE_BYNAME = 'GET_RECIPE_BYNAME';
export const GET_RECIPE_BYINGREDIENT = 'GET_RECIPE_BYINGREDIENT';
export const CREATE_NEW_RECIPE = 'CREATE_NEW_RECIPE';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';